Support sending product subscriptions
parameter1/omeda pull request #28
Opened 2022-07-07 16:21 UTC by solocommand

Now supports sending along explicitly defined [product subscriptions](https://training.omeda.com/knowledge-base/save-customer-and-order/#articleTOC_11) to support product fields within IdentityX.

Refactor Newsletter product handling to simplify flow

2022-07-07 16:22 UTC, solocommand commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add support for `product` as an external id entity type to facilitate Omeda product subscriptions](https://trello.com/c/kMo563wd/20-add-support-for-product-as-an-external-id-entity-type-to-facilitate-omeda-product-subscriptions)

2022-07-12 14:56 UTC, zarathustra323 requested changes

2022-07-12 14:56 UTC, zarathustra323 commented on services/graphql/src/resolvers/customer.js
> +        Products.push({ OmedaProductId: id, Receive: Number(receive) });
Account for newsletter product types of `2` and add to the deployment type optin/optout map (if not already present in the map)

2022-07-12 20:29 UTC, zarathustra323 approved these changes

2022-07-12 20:29 UTC, merged