Support Behaviors and related data
parameter1/omeda pull request #29
Opened 2022-07-21 20:09 UTC by solocommand

- Adds CLI to run actions, and adds actions to create IdentityX behavior elements
- Adds support to the Omeda API client for Brand Behaviors, Actions, Categories, and Attributes.
- Adds Brand Behavior repos for the same
- Expands sync logic for brand comp data for use with behavior data
- Support displaying and updating customer behaviors via the rapid identification mutation

2022-07-21 20:10 UTC, solocommand commented
![](https://github.trello.services/images/mini-trello-icon.png) [Utilize Behaviors for tracking verification status in Omeda](https://trello.com/c/qUfrU3v2/22-utilize-behaviors-for-tracking-verification-status-in-omeda)

2022-07-25 18:48 UTC, zarathustra323 requested changes

2022-07-25 18:48 UTC, zarathustra323 commented on packages/api-client/src/resources/brand.js
> +    return new BrandBehaviorLookupResponse({ response, resource: this });
Change all behavior lookups to `{ errorOnNotFound: false }`

2022-07-25 18:48 UTC, zarathustra323 commented on services/graphql/src/definitions/customer.js
> +  behaviorIds: [Int!] = []
`[Int!]! = []`

2022-07-25 19:11 UTC, zarathustra323 approved these changes

2022-07-25 19:12 UTC, merged